server:
  port: 8080
spring:
  application:
    name: sky-membership-service
  cloud:
    stream:
      bindings:
        output:
          destination: RetentionNotification
        reportRequest:
          destination: ClientDataRequest
        reportResponse:
          destination: ClientDataResponse


retention:
  threshold: 200


